language: go
go:
  - 1.15.x

services:
  - mysql

dist: xenial

env:
  - GO111MODULE=on ENV_PATH=/home/travis/gopath/src/github.com/Diwamoto/yource/backend/.travis/.env

before_install:
  - cd backend

script: 
  - go mod tidy
  - mysql -u travis -e 'CREATE DATABASE test_yource DEFAULT CHARACTER SET utf8mb4;'
  - cp .travis/.env ./env
  - go test ./... -v -count=1

notifications:
  email: false