language: go
go:
  - 1.16.x

services:
  - mysql

dist: xenial

env:
  - GO111MODULE=on ENV_PATH=/home/travis/gopath/src/github.com/Diwamoto/yource/backend/.travis/.env

before_install:
  - cd /
  - go install github.com/mattn/goveralls@latest
  - cd /home/travis/gopath/src/github.com/Diwamoto/yource/backend/

script: 
  - go mod tidy
  - mysql -u travis -e 'CREATE DATABASE test_yource DEFAULT CHARACTER SET utf8mb4;'
  - cp .travis/.env ./env
  - go test ./test/model/... -v -covermode=count -coverprofile=model.out -coverpkg=./model
  - goveralls -coverprofile=model.out -service=travis-ci -repotoken mHNbLYbbcny5kU3e09cdWOOV0Tjv0v3jx
  - go test ./test/config/... -v -covermode=count -coverprofile=config.out -coverpkg=./config
  - goveralls -coverprofile=model.out -service=travis-ci -repotoken mHNbLYbbcny5kU3e09cdWOOV0Tjv0v3jx

notifications:
  email: false