language: go
go:
  - 1.15.x

env:
  - GO111MODULE=on

script: 
  - go mod tidy
  - mysql -e 'CREATE DATABASE test_yource;'
  - cp ./backend/.travis/.env ./env
  - cd backend
  - go test ./... -v -count=1