language: go
go:
  - 1.15.x

env:
  - GO111MODULE=on

before_install:
  - cd backend

script: 
  - go mod tidy
  - mysql -u travis -e 'CREATE DATABASE test_yource;'
  - cp .travis/.env ./env
  - go test ./... -v -count=1