version: '2'
services:
  db:
    container_name: db
    image: mysql:5.7
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: "projects"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./db/mysql/conf.d:/etc/mysql/conf.d
      - ./db/logs/mysql:/var/log/mysql
      - ./db/mysql_data:/var/lib/mysql
  backend:
    container_name: go
    tty: true
    build:
      context: ./
      dockerfile: ./go/Dockerfile
    ports:
      - '9091:9091'
      # - '2345:2345'
    command: gin -p 9091
    volumes:
      - ../backend:/go/app
  frontend:
    container_name: vue
    tty: true
    build:
      context: ./
      dockerfile: ./vue/Dockerfile
    command: bash -c "npm install && npm run dev"
    ports:
      - '9092:9092'
    volumes:
      - ../frontend:/app
  nginx:
    container_name: nginx
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - "backend"
      - "frontend"
      - "adminer"
    volumes:
      - ./nginx/log:/var/log/nginx
  adminer:
    container_name: adminer
    image: adminer:latest
    ports:
      - "8080:8080"
    depends_on:
      - "db"
